# Generated by Django 3.2 on 2021-05-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/%y/%m/%d/'),
        ),
    ]
